language: python

python:
  - 3.6

env:
  - DJANGO=1.9.4

install:
  - pip install -r requirements.txt

script:
  - cp coaxialowl/local_settings_copy.py coaxialowl/local_settings.py
  - python manage.py check
  - python manage.py migrate --noinput
